-- update_sloka_scripture_ids.sql — generated by scripts/map_sloka_scriptures.py
-- Sets scripture_id on sloka rows where the scripture_ref matches a known scripture.
-- Safe to re-run (UPDATE is idempotent). scripture_id is NULL for unmatched rows.

SET NAMES utf8mb4;

-- Brihad Bhagavatamrita (BB) — 19 slokas
UPDATE sloka SET scripture_id = 1 WHERE id IN (220, 221, 511, 744, 745, 750, 770, 772, 796, 851, 856, 944, 945, 946, 1105, 1106, 1115, 1116, 1117);

-- Bhagavad Gita (BG) — 64 slokas
UPDATE sloka SET scripture_id = 2 WHERE id IN (28, 96, 107, 114, 126, 127, 172, 173, 174, 175, 204, 205, 265, 266, 267, 271, 272, 279, 280, 282, 338, 339, 346, 354, 361, 362, 363, 365, 366, 397, 398, 412, 415, 426, 437, 442, 443, 444, 450, 486, 487, 497, 504, 553, 564, 569, 580, 582, 584, 614, 615, 618, 623, 656, 657, 658, 659, 665, 692, 693, 895, 1029, 1069, 1077);

-- Srimad Bhagavad Gita (SBG) — 4 slokas
UPDATE sloka SET scripture_id = 3 WHERE id IN (281, 451, 573, 581);

-- Bhajana Rahasya (BR) — 7 slokas
UPDATE sloka SET scripture_id = 5 WHERE id IN (378, 391, 708, 735, 736, 802, 997);

-- Bhakti Rasamrita Sindhu (BRS) — 41 slokas
UPDATE sloka SET scripture_id = 6 WHERE id IN (19, 56, 87, 423, 453, 455, 456, 461, 464, 465, 466, 467, 469, 471, 472, 535, 539, 541, 548, 560, 572, 597, 598, 613, 624, 625, 653, 716, 763, 798, 803, 810, 833, 834, 852, 878, 891, 909, 910, 955, 992);

-- Bhakti Rasamrita Sindhu Bindhu (BRSB) — 2 slokas
UPDATE sloka SET scripture_id = 7 WHERE id IN (212, 1091);

-- Brahma Samhita (BS) — 13 slokas
UPDATE sloka SET scripture_id = 8 WHERE id IN (253, 259, 262, 273, 337, 340, 387, 388, 394, 610, 611, 849, 970);

-- Bhakti Tattva Viveka (BTV) — 1 slokas
UPDATE sloka SET scripture_id = 9 WHERE id IN (419);

-- Caitanya Bhagavata (CB) — 17 slokas
UPDATE sloka SET scripture_id = 10 WHERE id IN (153, 161, 181, 223, 234, 235, 240, 241, 250, 530, 595, 730, 732, 733, 738, 746, 778);

-- Caitanya Caritamrita (CC) — 2 slokas
UPDATE sloka SET scripture_id = 11 WHERE id IN (65, 756);

-- Caitanya Caritamrita - Adi Lila (CC Adi) — 93 slokas
UPDATE sloka SET scripture_id = 12 WHERE id IN (4, 5, 6, 18, 36, 37, 38, 40, 58, 62, 68, 90, 99, 155, 184, 185, 186, 187, 188, 191, 192, 193, 196, 198, 209, 218, 228, 230, 232, 236, 237, 238, 239, 242, 243, 246, 247, 249, 261, 263, 264, 269, 276, 283, 284, 285, 324, 325, 326, 330, 332, 457, 494, 552, 568, 641, 705, 709, 710, 711, 751, 759, 789, 809, 836, 837, 838, 839, 840, 841, 842, 843, 844, 854, 892, 893, 894, 897, 898, 899, 902, 904, 929, 964, 966, 968, 969, 971, 973, 976, 1026, 1032, 1072);

-- Caitanya Caritamrita - Madhya Lila (CC Mad) — 119 slokas
UPDATE sloka SET scripture_id = 13 WHERE id IN (31, 32, 34, 44, 95, 97, 98, 100, 102, 119, 121, 123, 125, 149, 150, 151, 152, 158, 160, 190, 200, 201, 208, 210, 211, 286, 287, 289, 290, 291, 303, 304, 327, 328, 329, 331, 343, 347, 348, 350, 351, 352, 356, 358, 359, 377, 381, 416, 424, 429, 446, 458, 459, 462, 463, 468, 470, 474, 479, 493, 495, 507, 508, 513, 514, 521, 523, 534, 538, 540, 546, 547, 577, 617, 634, 690, 748, 777, 786, 787, 808, 817, 847, 848, 850, 853, 883, 887, 888, 889, 890, 906, 914, 923, 937, 938, 939, 941, 951, 1008, 1014, 1033, 1044, 1045, 1046, 1047, 1048, 1049, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1086, 1089);

-- Caitanya Caritamrita - Antya Lila (CC Antya) — 16 slokas
UPDATE sloka SET scripture_id = 14 WHERE id IN (101, 106, 231, 439, 492, 544, 545, 602, 642, 666, 687, 767, 952, 1066, 1067, 1068);

-- Gita Govinda (GG) — 3 slokas
UPDATE sloka SET scripture_id = 15 WHERE id IN (963, 989, 1098);

-- Gaudiya Kanthahara (GKH) — 1 slokas
UPDATE sloka SET scripture_id = 16 WHERE id IN (177);

-- Hari Bhakti Vilasa (HBV) — 19 slokas
UPDATE sloka SET scripture_id = 17 WHERE id IN (41, 45, 52, 54, 80, 81, 86, 88, 222, 485, 715, 734, 768, 985, 1016, 1092, 1093, 1094, 1095);

-- Manah Siksa (MS) — 17 slokas
UPDATE sloka SET scripture_id = 21 WHERE id IN (43, 475, 476, 643, 655, 698, 699, 877, 954, 975, 1006, 1073, 1083, 1084, 1085, 1110, 1111);

-- Prapanna Jivanamritam (PJ) — 1 slokas
UPDATE sloka SET scripture_id = 23 WHERE id IN (489);

-- Radha Rasa Sudha Nidhi (RRSN) — 10 slokas
UPDATE sloka SET scripture_id = 26 WHERE id IN (982, 983, 995, 1002, 1003, 1004, 1005, 1009, 1017, 1020);

-- Srimad Bhagavatam (SB) — 293 slokas
UPDATE sloka SET scripture_id = 27 WHERE id IN (11, 20, 21, 23, 25, 39, 46, 47, 55, 59, 60, 69, 72, 73, 91, 92, 94, 103, 104, 105, 108, 109, 110, 115, 117, 118, 120, 122, 124, 128, 130, 135, 138, 139, 140, 141, 142, 143, 144, 145, 147, 148, 157, 162, 163, 164, 166, 167, 168, 169, 170, 171, 176, 178, 179, 180, 194, 195, 199, 202, 254, 255, 256, 258, 260, 275, 278, 296, 297, 299, 300, 301, 302, 314, 315, 334, 335, 336, 364, 399, 400, 401, 407, 409, 411, 413, 414, 417, 418, 420, 421, 422, 427, 428, 430, 431, 433, 435, 438, 445, 449, 452, 454, 482, 483, 484, 509, 510, 515, 517, 526, 527, 529, 533, 543, 551, 558, 559, 561, 562, 563, 565, 567, 570, 571, 575, 576, 578, 579, 583, 585, 586, 587, 588, 589, 590, 591, 592, 594, 600, 601, 603, 604, 605, 606, 607, 608, 609, 612, 621, 622, 629, 630, 631, 632, 635, 636, 637, 638, 639, 640, 644, 645, 646, 647, 648, 650, 651, 660, 661, 662, 663, 664, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 688, 689, 696, 697, 707, 719, 723, 724, 726, 752, 766, 773, 774, 775, 776, 780, 781, 782, 790, 791, 792, 801, 805, 806, 811, 813, 814, 816, 818, 819, 820, 821, 822, 823, 824, 825, 826, 828, 829, 830, 835, 845, 855, 862, 863, 864, 865, 866, 867, 868, 871, 872, 873, 874, 875, 876, 884, 885, 886, 896, 900, 901, 903, 905, 907, 908, 911, 913, 915, 916, 917, 919, 920, 928, 932, 933, 934, 935, 936, 940, 947, 953, 956, 961, 962, 974, 993, 1025, 1030, 1034, 1071, 1078, 1079, 1080, 1081, 1088, 1100, 1101, 1102, 1103, 1121);

-- Sri Gaudiya Giti Guccha (SGGG) — 4 slokas
UPDATE sloka SET scripture_id = 28 WHERE id IN (79, 227, 309, 333);

-- Siksastaka (SS) — 9 slokas
UPDATE sloka SET scripture_id = 29 WHERE id IN (491, 654, 701, 717, 761, 800, 912, 950, 991);

-- Venu Gita (VG) — 2 slokas
UPDATE sloka SET scripture_id = 30 WHERE id IN (1123, 1124);

-- Vilapa Kusumanjalih (VK) — 12 slokas
UPDATE sloka SET scripture_id = 31 WHERE id IN (477, 804, 984, 1010, 1011, 1012, 1015, 1050, 1064, 1065, 1109, 1118);

-- Upadesamrita (Upad.) — 11 slokas
UPDATE sloka SET scripture_id = 32 WHERE id IN (30, 112, 113, 447, 524, 549, 550, 593, 978, 979, 980);

-- Adi Purana (ADIP) — 2 slokas
UPDATE sloka SET scripture_id = 33 WHERE id IN (136, 652);

-- Aditya Purana (ADTY) — 1 slokas
UPDATE sloka SET scripture_id = 34 WHERE id IN (70);

-- Amnaya Sutra (AMNS) — 6 slokas
UPDATE sloka SET scripture_id = 35 WHERE id IN (368, 369, 370, 371, 480, 481);

-- Ananta Samhita (ANTS) — 1 slokas
UPDATE sloka SET scripture_id = 36 WHERE id IN (225);

-- Atma Nivedana (ATNV) — 1 slokas
UPDATE sloka SET scripture_id = 37 WHERE id IN (574);

-- Bhagavat Sandarbha (BHGS) — 2 slokas
UPDATE sloka SET scripture_id = 38 WHERE id IN (385, 386);

-- Bhajahu Re Mana (BHRM) — 1 slokas
UPDATE sloka SET scripture_id = 39 WHERE id IN (434);

-- Bhakti Ratnakara (BHRK) — 1 slokas
UPDATE sloka SET scripture_id = 40 WHERE id IN (981);

-- Bhakti Sandarbha (BHSN) — 8 slokas
UPDATE sloka SET scripture_id = 41 WHERE id IN (53, 132, 133, 403, 408, 448, 769, 793);

-- Bhavartha Dipika (BHDI) — 1 slokas
UPDATE sloka SET scripture_id = 42 WHERE id IN (78);

-- Bhavishya Purana (BHVP) — 1 slokas
UPDATE sloka SET scripture_id = 43 WHERE id IN (870);

-- Brahmanda Purana (BRMP) — 1 slokas
UPDATE sloka SET scripture_id = 44 WHERE id IN (713);

-- Brihad Aranyaka Upanishad (BAUP) — 1 slokas
UPDATE sloka SET scripture_id = 45 WHERE id IN (355);

-- Brihad Gautamiya Tantra (BGTN) — 1 slokas
UPDATE sloka SET scripture_id = 46 WHERE id IN (972);

-- Brihad Vishnu Purana (BVSP) — 1 slokas
UPDATE sloka SET scripture_id = 47 WHERE id IN (714);

-- Brihan Naradiya Purana (BNRP) — 3 slokas
UPDATE sloka SET scripture_id = 48 WHERE id IN (404, 516, 704);

-- Brihat Bhakti Tattva Sara (BBTS) — 1 slokas
UPDATE sloka SET scripture_id = 49 WHERE id IN (82);

-- Caitanya Candramrita (CCAM) — 6 slokas
UPDATE sloka SET scripture_id = 50 WHERE id IN (197, 213, 214, 215, 216, 1074);

-- Caitanya Candrodaya Nataka (CCNT) — 2 slokas
UPDATE sloka SET scripture_id = 51 WHERE id IN (1037, 1038);

-- Caitanya Mangala (CMGL) — 1 slokas
UPDATE sloka SET scripture_id = 52 WHERE id IN (405);

-- Caitanya Manjusa (CMNJ) — 1 slokas
UPDATE sloka SET scripture_id = 53 WHERE id IN (189);

-- Cauragraganya Purusastakam (CAUP) — 1 slokas
UPDATE sloka SET scripture_id = 54 WHERE id IN (1099);

-- Chandogya Upanishad (CHUP) — 5 slokas
UPDATE sloka SET scripture_id = 55 WHERE id IN (27, 295, 376, 395, 880);

-- Dana Keli Cintamani (DKC) — 1 slokas
UPDATE sloka SET scripture_id = 56 WHERE id IN (1040);

-- Dasa Mula Tattva (DMT) — 17 slokas
UPDATE sloka SET scripture_id = 57 WHERE id IN (257, 277, 288, 320, 344, 345, 384, 512, 542, 555, 702, 799, 832, 879, 1022, 1023, 1024);

-- Gadadharastakam (GDAST) — 1 slokas
UPDATE sloka SET scripture_id = 58 WHERE id IN (251);

-- Gandharva Samprarthanastakam (GSAST) — 2 slokas
UPDATE sloka SET scripture_id = 59 WHERE id IN (15, 1097);

-- Garga Samhita (GASM) — 1 slokas
UPDATE sloka SET scripture_id = 60 WHERE id IN (61);

-- Garuda Purana (GRDP) — 3 slokas
UPDATE sloka SET scripture_id = 61 WHERE id IN (146, 440, 722);

-- Gaura Ganoddesadipika (GGDP) — 1 slokas
UPDATE sloka SET scripture_id = 62 WHERE id IN (244);

-- Gauranga Balite Habe (GBH) — 1 slokas
UPDATE sloka SET scripture_id = 63 WHERE id IN (478);

-- Gautamiya Tantra (GTAN) — 1 slokas
UPDATE sloka SET scripture_id = 64 WHERE id IN (245);

-- Gita Mala (GTML) — 1 slokas
UPDATE sloka SET scripture_id = 65 WHERE id IN (846);

-- Gitavali (GTAV) — 1 slokas
UPDATE sloka SET scripture_id = 66 WHERE id IN (1070);

-- Gopala Sahasra Nama (GSNAM) — 1 slokas
UPDATE sloka SET scripture_id = 67 WHERE id IN (310);

-- Gopinatha (GOPIN) — 1 slokas
UPDATE sloka SET scripture_id = 68 WHERE id IN (694);

-- Govardhana Vasa Prarthana (GVPR) — 1 slokas
UPDATE sloka SET scripture_id = 69 WHERE id IN (869);

-- Guru Carana Padma (GCPAD) — 1 slokas
UPDATE sloka SET scripture_id = 70 WHERE id IN (84);

-- Gurudeva Krpa Bindu Diya (GKBD) — 1 slokas
UPDATE sloka SET scripture_id = 71 WHERE id IN (85);

-- Gurvastakam (GVAST) — 3 slokas
UPDATE sloka SET scripture_id = 72 WHERE id IN (26, 29, 33);

-- Hamsaduta (HAMS) — 1 slokas
UPDATE sloka SET scripture_id = 73 WHERE id IN (921);

-- Hari Bhakti Sudhodaya (HBSU) — 4 slokas
UPDATE sloka SET scripture_id = 74 WHERE id IN (111, 441, 522, 596);

-- Hitopadesa (HITO) — 1 slokas
UPDATE sloka SET scripture_id = 75 WHERE id IN (436);

-- Isopanishad (ISOP) — 4 slokas
UPDATE sloka SET scripture_id = 76 WHERE id IN (274, 390, 396, 616);

-- Jagannatha Vallabha Nataka (JVNAT) — 1 slokas
UPDATE sloka SET scripture_id = 77 WHERE id IN (922);

-- Jaladakhyana Samhita (JALS) — 1 slokas
UPDATE sloka SET scripture_id = 78 WHERE id IN (42);

-- Je Anila Prema Dhana (JAPD) — 1 slokas
UPDATE sloka SET scripture_id = 79 WHERE id IN (248);

-- Jiva Jago (JIVJ) — 1 slokas
UPDATE sloka SET scripture_id = 80 WHERE id IN (743);

-- Kali Kukkura Kadana (KKKAD) — 1 slokas
UPDATE sloka SET scripture_id = 81 WHERE id IN (224);

-- Kali Santarana Upanishad (KSUP) — 1 slokas
UPDATE sloka SET scripture_id = 82 WHERE id IN (731);

-- Katha Upanishad (KATHU) — 4 slokas
UPDATE sloka SET scripture_id = 83 WHERE id IN (48, 49, 116, 268);

-- Katyayana Samhita (KATS) — 1 slokas
UPDATE sloka SET scripture_id = 84 WHERE id IN (536);

-- Krama Dipika (KRMD) — 2 slokas
UPDATE sloka SET scripture_id = 85 WHERE id IN (749, 762);

-- Krishna Karnamrita (KKAM) — 11 slokas
UPDATE sloka SET scripture_id = 86 WHERE id IN (35, 317, 319, 812, 831, 924, 925, 926, 927, 959, 960);

-- Krishna Nama Dhare Kata Bala (KNDB) — 2 slokas
UPDATE sloka SET scripture_id = 87 WHERE id IN (379, 785);

-- Krishna Sandarbha (KSAN) — 2 slokas
UPDATE sloka SET scripture_id = 88 WHERE id IN (794, 795);

-- Krishna Virahe (KRVIR) — 1 slokas
UPDATE sloka SET scripture_id = 89 WHERE id IN (948);

-- Krpa Kara Vaishnava Thakura (KKVT) — 1 slokas
UPDATE sloka SET scripture_id = 90 WHERE id IN (76);

-- Kunja Bihari Astakam (KBAST) — 1 slokas
UPDATE sloka SET scripture_id = 91 WHERE id IN (316);

-- Laghu Bhagavatamrita (LBAG) — 2 slokas
UPDATE sloka SET scripture_id = 92 WHERE id IN (294, 649);

-- Lalita Madhava (LMAD) — 2 slokas
UPDATE sloka SET scripture_id = 93 WHERE id IN (930, 931);

-- Mahabharata (MAHB) — 4 slokas
UPDATE sloka SET scripture_id = 94 WHERE id IN (51, 131, 203, 1031);

-- Mahajana Racita Gita (MRGIT) — 2 slokas
UPDATE sloka SET scripture_id = 95 WHERE id IN (383, 771);

-- Mukta Carita (MUKC) — 1 slokas
UPDATE sloka SET scripture_id = 96 WHERE id IN (77);

-- Mukunda Mala Stotra (MMST) — 3 slokas
UPDATE sloka SET scripture_id = 97 WHERE id IN (488, 499, 754);

-- Mukunda Muktavali (MUKM) — 2 slokas
UPDATE sloka SET scripture_id = 98 WHERE id IN (305, 306);

-- Mundaka Upanishad (MUND) — 5 slokas
UPDATE sloka SET scripture_id = 99 WHERE id IN (22, 519, 525, 1027, 1028);

-- Nama Sankirtana (NMSK) — 1 slokas
UPDATE sloka SET scripture_id = 100 WHERE id IN (700);

-- Namastaka (NAST) — 2 slokas
UPDATE sloka SET scripture_id = 101 WHERE id IN (718, 737);

-- Narada Pancaratra (NPAN) — 5 slokas
UPDATE sloka SET scripture_id = 102 WHERE id IN (342, 353, 554, 557, 1082);

-- Naradiya Purana (NPUR) — 3 slokas
UPDATE sloka SET scripture_id = 103 WHERE id IN (134, 628, 765);

-- Navadvipa Dhama Mahatmya (NDM) — 1 slokas
UPDATE sloka SET scripture_id = 104 WHERE id IN (760);

-- Navadvipa Sataka (NSAT) — 2 slokas
UPDATE sloka SET scripture_id = 105 WHERE id IN (219, 1104);

-- Nikunja Rahasya Stava (NRS) — 1 slokas
UPDATE sloka SET scripture_id = 106 WHERE id IN (1096);

-- Nityananda Nistha Prarthana (NNP) — 1 slokas
UPDATE sloka SET scripture_id = 107 WHERE id IN (233);

-- Nityanandastakam (NITAS) — 1 slokas
UPDATE sloka SET scripture_id = 108 WHERE id IN (229);

-- Padma Purana (PADP) — 21 slokas
UPDATE sloka SET scripture_id = 109 WHERE id IN (67, 74, 75, 156, 318, 382, 432, 496, 531, 703, 706, 721, 725, 753, 755, 757, 784, 949, 965, 1113, 1114);

-- Padyavali (PADY) — 15 slokas
UPDATE sloka SET scripture_id = 110 WHERE id IN (129, 159, 312, 313, 460, 695, 807, 857, 858, 859, 860, 861, 918, 957, 958);

-- Pancaratra Pradipa (PANP) — 1 slokas
UPDATE sloka SET scripture_id = 111 WHERE id IN (986);

-- Paramatma Sandarbha (PASAN) — 4 slokas
UPDATE sloka SET scripture_id = 112 WHERE id IN (373, 374, 375, 392);

-- Paurnamasi Devi Pranama (PDPRA) — 1 slokas
UPDATE sloka SET scripture_id = 113 WHERE id IN (1119);

-- Prameya Ratnavali (PRAMR) — 1 slokas
UPDATE sloka SET scripture_id = 114 WHERE id IN (1036);

-- Prema Bhakti Chandrika (PBCH) — 5 slokas
UPDATE sloka SET scripture_id = 115 WHERE id IN (3, 599, 620, 1018, 1041);

-- Prema Vivarta (PVIV) — 4 slokas
UPDATE sloka SET scripture_id = 116 WHERE id IN (349, 532, 686, 742);

-- Radha Bhajana Mahima (RBHM) — 1 slokas
UPDATE sloka SET scripture_id = 117 WHERE id IN (998);

-- Radha Kripa Kataksha Stava Raja (RKKS) — 2 slokas
UPDATE sloka SET scripture_id = 118 WHERE id IN (990, 1021);

-- Radha Krishna Vijnapti (RKVJ) — 1 slokas
UPDATE sloka SET scripture_id = 119 WHERE id IN (626);

-- Radha Prarthana (RADP) — 2 slokas
UPDATE sloka SET scripture_id = 120 WHERE id IN (14, 1007);

-- Radhika Carana Padma (RCPAD) — 1 slokas
UPDATE sloka SET scripture_id = 121 WHERE id IN (999);

-- Radhikastakam (RAST) — 1 slokas
UPDATE sloka SET scripture_id = 122 WHERE id IN (988);

-- Rig Veda (RGVED) — 2 slokas
UPDATE sloka SET scripture_id = 123 WHERE id IN (93, 729);

-- Rupa Manjari Pada (RMPAD) — 1 slokas
UPDATE sloka SET scripture_id = 124 WHERE id IN (943);

-- Sad Anga Saranagati (SASAR) — 1 slokas
UPDATE sloka SET scripture_id = 125 WHERE id IN (490);

-- Sammohana Tantra (SAMT) — 1 slokas
UPDATE sloka SET scripture_id = 126 WHERE id IN (341);

-- Sanat Kumara Samhita (SKSAM) — 3 slokas
UPDATE sloka SET scripture_id = 127 WHERE id IN (292, 977, 1019);

-- Sandilya Bhakti Sutra (SBSUT) — 1 slokas
UPDATE sloka SET scripture_id = 128 WHERE id IN (556);

-- Saranagati (SARAN) — 1 slokas
UPDATE sloka SET scripture_id = 129 WHERE id IN (528);

-- Sata Nama Stotra (SNST) — 1 slokas
UPDATE sloka SET scripture_id = 130 WHERE id IN (712);

-- Skanda Purana (SKP) — 5 slokas
UPDATE sloka SET scripture_id = 131 WHERE id IN (165, 402, 520, 720, 739);

-- Sri Radha Nistha (SRNIS) — 1 slokas
UPDATE sloka SET scripture_id = 132 WHERE id IN (633);

-- Stava Kalpadruma (STVK) — 1 slokas
UPDATE sloka SET scripture_id = 133 WHERE id IN (83);

-- Stava Mala (STVM) — 10 slokas
UPDATE sloka SET scripture_id = 134 WHERE id IN (13, 537, 727, 728, 987, 1060, 1061, 1062, 1063, 1108);

-- Stavavali (STAV) — 9 slokas
UPDATE sloka SET scripture_id = 135 WHERE id IN (16, 17, 217, 797, 942, 996, 1000, 1039, 1042);

-- Stotra Ratna (STRAT) — 1 slokas
UPDATE sloka SET scripture_id = 136 WHERE id IN (503);

-- Sva Sankalpa Prakasa Stotra (SSPS) — 2 slokas
UPDATE sloka SET scripture_id = 137 WHERE id IN (994, 1001);

-- Svarupa Damodara's Diary (SDDIA) — 2 slokas
UPDATE sloka SET scripture_id = 138 WHERE id IN (154, 226);

-- Svarupa Damodara's Kadaca (SDKAD) — 1 slokas
UPDATE sloka SET scripture_id = 139 WHERE id IN (183);

-- Svetasvatara Upanishad (SVUP) — 6 slokas
UPDATE sloka SET scripture_id = 140 WHERE id IN (24, 321, 357, 360, 367, 372);

-- Taittiriya Upanishad (TAUP) — 1 slokas
UPDATE sloka SET scripture_id = 141 WHERE id IN (393);

-- Tattva Sandarbha (TATS) — 1 slokas
UPDATE sloka SET scripture_id = 142 WHERE id IN (207);

-- Thakura Vaishnava Pada (TVP) — 1 slokas
UPDATE sloka SET scripture_id = 143 WHERE id IN (627);

-- Tri Bhangi Pancakam (TBP) — 2 slokas
UPDATE sloka SET scripture_id = 144 WHERE id IN (307, 308);

-- Ujjvala Nilamani (UNIL) — 2 slokas
UPDATE sloka SET scripture_id = 145 WHERE id IN (473, 967);

-- Uttara Gopala Tapani Upanishad (UGTU) — 1 slokas
UPDATE sloka SET scripture_id = 146 WHERE id IN (788);

-- Vaishnava Tantra (VATN) — 1 slokas
UPDATE sloka SET scripture_id = 147 WHERE id IN (881);

-- Vaishvanara Samhita (VSHS) — 1 slokas
UPDATE sloka SET scripture_id = 148 WHERE id IN (740);

-- Vamana Kalpa (VAMK) — 1 slokas
UPDATE sloka SET scripture_id = 149 WHERE id IN (66);

-- Varaha Purana (VARP) — 1 slokas
UPDATE sloka SET scripture_id = 150 WHERE id IN (137);

-- Vedanta Sutra (VEDS) — 2 slokas
UPDATE sloka SET scripture_id = 151 WHERE id IN (380, 389);

-- Vidagdha Madhava (VDMAD) — 3 slokas
UPDATE sloka SET scripture_id = 152 WHERE id IN (182, 741, 1122);

-- Vishnu Purana (VISP) — 5 slokas
UPDATE sloka SET scripture_id = 153 WHERE id IN (57, 270, 298, 323, 410);

-- Vishnu Yamala (VISY) — 2 slokas
UPDATE sloka SET scripture_id = 154 WHERE id IN (63, 882);

-- Vraja Vilasa Stava (VVST) — 3 slokas
UPDATE sloka SET scripture_id = 155 WHERE id IN (252, 827, 1120);

-- Vrinda Devi Astakam (VDAST) — 1 slokas
UPDATE sloka SET scripture_id = 156 WHERE id IN (12);

-- Vrindavana Mahimamrita (VRMA) — 2 slokas
UPDATE sloka SET scripture_id = 157 WHERE id IN (1013, 1107);

-- Yamuna Stotram (YSTOT) — 3 slokas
UPDATE sloka SET scripture_id = 158 WHERE id IN (501, 502, 691);

-- Yamunastakam (YAST) — 1 slokas
UPDATE sloka SET scripture_id = 159 WHERE id IN (1112);

-- ── Unmatched (left as NULL) ─────────────────────────────────────────────────
-- [  2]  Bilvanamgala Thakura, Govinda Damodara Madhavreti stotram
-- [  1]  Purāṇa-vākya
-- [  1]  Ei-Bāra Karuṇā Kara
-- [  1]  āgama-śāstras
-- [  1]  sri krishna dyanam
-- [  1]  Smṛti Vākya
-- [  1]  E Mana! 'Harinām' Koro Sāra 3
-- [  1]  From the teachings of Śrīla Bhakti Prajñāna Keśava Gosvāmī
-- [  1]  Śrī Yamunacarya
-- [  1]  Māthara śruti
-- [  1]  Bengali poetry
-- [  1]  source unknown
-- [  1]  Duṣta mana! Śrīla Bhaktisiddhānta Sarasvatī Prabhupāda
-- [  1]  Śrī Caitanya Mahāprabhu's Bhagavtā Pramāṇa (Hindi)
-- [  1]  Manu 12.105
-- [  1]  Yan Kali Rūpa
-- [  1]  Bilvamaṅgala Ṭhākura
-- [  1]  Śaṅkarācārya
-- [  1]  Śrīdhara Swāmī

-- Done: 1089 matched, 20 unmatched, 17 had no ref.